### ISSUE TITLE
Telefon Numaraları kontrol edilecek

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#10]
* Post olarak gönderilen telefon numaraları çok basitçe kontrol edin 
*  0 ile başlama zorunluluğu olmasın onu tolere edecek bir fonksiyon yazın

**Comment by BeratNzp** [comment]
Selam @izzetemredemir kontrolden kastımız nedir tam olarak ayrıntı verebilir misin ?
Basit bir formatlama mı yoksa başka bir şey mi ?

**Comment by endrcn** [comment]
Ben bir PR açtım, kontrol edebilir misiniz? Düzenleme ihtiyacı olursa hızlıca yaparım.

**Comment by mehmetik** [comment]
#18 #17  double check 👍
