### ISSUE TITLE
Telefon Numarasının Internal Server Error'a yol açması(???)

### ISSUE THREAD

**Issue by hackerone-yusuf** [acikkaynak/deprem-io-backend#100]
Requestte telefon numarası boş girildiğinde 1/undefined hatasına yol açıyor.

![image](https://user-images.githubusercontent.com/124896653/218199115-d8baf143-fb68-43db-a084-1801a441e157.png)

Sonrasında veriler için request edildiğinde:

Request öncesi (enkaz)
![image](https://user-images.githubusercontent.com/124896653/218200134-d00c4959-379d-449e-8f5d-6c03ca4d4b10.png)

Request sonrası (enkaz)
![image](https://user-images.githubusercontent.com/124896653/218200211-4da45336-3bf0-4855-ade6-5848958479c5.png)

Request öncesi (gıda)
![image](https://user-images.githubusercontent.com/124896653/218200439-dd19d286-cf16-4862-86a6-604203367594.png)

Request sonrası(gıda)
![image](https://user-images.githubusercontent.com/124896653/218200869-331c274f-77b3-4167-9147-f4478db30510.png)

Örnek request:
![image](https://user-images.githubusercontent.com/124896653/218204345-b32a067f-b202-47a3-a00e-9ebf7ad6732d.png)

**Comment by hackerone-yusuf** [comment]
Özellikle ısınmaya request atmadım ama şu an onda da aynı hata veriyor.

**Comment by anonrig** [comment]
Problem cozuldu. Kapatiyorum.

**Comment by hackerone-yusuf** [comment]
> Problem cozuldu. Kapatiyorum.

retest ettikten sonra kapatmayı planlıyordum da buradaki hata devam ediyor, ayrı issue mu açayım
![image](https://user-images.githubusercontent.com/124896653/218225342-811549ba-347b-41ba-bf2c-4974c9ef52ca.png)

**Comment by hackerone-yusuf** [comment]
![image](https://user-images.githubusercontent.com/124896653/218225684-e92cbc18-21fd-466e-bc2e-eba2e6ba2d8f.png)
![image](https://user-images.githubusercontent.com/124896653/218225722-3d230585-7507-49b3-951d-811c89487b45.png)

**Comment by endrcn** [comment]
@anonrig @izzetemredemir Bu hataların trace'lerine bakabileceğimiz bir yer var mı? Bu tip sorunları tespit edip çözebilmemiz daha kolay olurdu.
