### ISSUE TITLE
MVC Sonrası Cache instance import hatası.

### ISSUE THREAD

**Issue by mehmetik** [acikkaynak/deprem-io-backend#104]
MVC'ye çevrildikten sonra ilgili cache içeriye eklenmemiş. Bundan dolayı patlama yaşatıyor.

{
"statusCode": 500,
"error": "Internal Server Error",
"message": "cache.getCache is not a function"
}

**Comment by cemasma** [comment]
https://github.com/acikkaynak/deprem-io-backend/pull/103 şu şekilde bir pr açtım fix için

**Comment by hackerone-yusuf** [comment]
#100 bununla alakalı mı ? Çünkü sanırım internal error vermesi attığım requestle eş zamanlı oldu.

**Comment by mehmetik** [comment]
> #100 bununla alakalı mı ? Çünkü sanırım internal error vermesi attığım requestle eş zamanlı oldu.

evet

**Comment by mehmetik** [comment]
Sorunlarla alakalı çözümleri buldum. PR atacağım.

**Comment by hackerone-yusuf** [comment]
Tamamdır, teşekkürler.

**Comment by nazmirket** [comment]
veritabanı bağlantısını index.js dosyasında sunucu başlarken tek sefer gerçekleştirmemiz daha iyi olmaz mı?

**Comment by nazmirket** [comment]
controller içerisine her işlemden önce db bağlantısını kontrol etmeye gerek var mı?

**Comment by nazmirket** [comment]
açtığım pr da ben bu kısma bir düzeltme yapmaya çalıştım

**Comment by cemasma** [comment]
> Sorunlarla alakalı çözümleri buldum. PR atacağım.

paylaşmış olduğum pr çözmüyor mu problemi?
