### ISSUE TITLE
"Cannot read properties of undefined (reading 'slice')" hatası

### ISSUE THREAD

**Issue by hackerone-yusuf** [acikkaynak/deprem-io-backend#109]
![image](https://user-images.githubusercontent.com/124896653/218225892-6c82cf50-f617-4a9a-a7dc-f2ec632d54ad.png)
![image](https://user-images.githubusercontent.com/124896653/218225903-76e39763-c486-4cf2-98a3-0e25dcc65035.png)

**Comment by mehmetik** [comment]
#106 master'ı checkout yapar mısın

**Comment by hackerone-yusuf** [comment]
Bir şeyi yanlış mı yapıyorum
![image](https://user-images.githubusercontent.com/124896653/218227382-5d216492-650d-4f07-bf64-7faa2df29068.png)
![image](https://user-images.githubusercontent.com/124896653/218227401-dbfad563-ac15-45b3-83e5-0ff271f0c59c.png)

**Comment by mehmetik** [comment]
Hayır sen yanlış yapmıyorsun hocam ara-yardim vs'de de varmış bu hata ondan dolayı görüyorsun. direk ara- olmadan bakarsan sorunsuz. /yardim için çözülmüştü. Tüm linkleri inceleyeyim ben hızlıca.

**Comment by hackerone-yusuf** [comment]
Tamamdır

**Comment by hackerone-yusuf** [comment]
Sorun bir süre önce çözülmüştü şu an devam ediyor.
![image](https://user-images.githubusercontent.com/124896653/218256718-8771a67e-1cab-44ad-a48e-122addbdf8e9.png)
![image](https://user-images.githubusercontent.com/124896653/218256721-301a00e1-9eee-490f-8c73-d88d1ca091c5.png)
![image](https://user-images.githubusercontent.com/124896653/218256729-35fdff57-1e51-416a-862e-9be7cc35d37c.png)
![image](https://user-images.githubusercontent.com/124896653/218256741-8a84073c-1b89-4433-9c24-6f91498dc403.png)

**Comment by hackerone-yusuf** [comment]
pardon
