### ISSUE TITLE
pr squash merge?

### ISSUE THREAD

**Issue by OkanPinar** [acikkaynak/deprem-io-backend#113]
Bazı pr larda gereksiz commit ler gözüküyor. Pr larda commit leri merge etmeden squash yapılması akışın takibini daha kolaylaştırabilir.

**Comment by Ertan222** [comment]
Katılıyorum, squash pull seçenekleri arasında en rahat ve takip edilebilir seçenek bence.

**Comment by izzetemredemir** [comment]
Tamamdır dikkat ederim
