### ISSUE TITLE
Twitter hariç link eklenebilmesi

### ISSUE THREAD

**Issue by hackerone-yusuf** [acikkaynak/deprem-io-backend#115]
Filtrelemiyor
![image](https://user-images.githubusercontent.com/124896653/218255018-fdc228a2-29c8-4058-adae-8169faa071a1.png)

**Comment by endrcn** [comment]
schema'ya bir pattern ekliyorum

**Comment by endrcn** [comment]
PR açıldı.

tweetLink field'i "twitter.com" pattern'i ile route schema'ya eklendi.

Fastify route schema'nın bir handikapı şu ki: Eğer veri boş string ya da null gönderilirse, pattern'e uymayacağı için hata fırlatıyor. Bu nedenle link alanı doldurulmadıysa body'e hiç eklenmemeli.

Görsel 1: twitter.com içermeyen URL
![image](https://user-images.githubusercontent.com/7888585/218256321-f7d1abae-0510-45c5-8807-2d0dca459f61.png)

Görsel 2: boş string
![image](https://user-images.githubusercontent.com/7888585/218256331-ce42e3a2-ad81-41b5-ae53-1f204acb85be.png)

Görsel 3: body'e hiç eklenmemesi (success)
![image](https://user-images.githubusercontent.com/7888585/218256382-9e5414e7-8b6b-427c-8e18-cf7442696dc3.png)

**Comment by endrcn** [comment]
Güncelleme: Fastify'da hata mesajını Türkçe gönderemediğim için tweetLink alanını route içinde kontrol ettim.

**Comment by hackerone-yusuf** [comment]
sorun şu an devam ediyor
![image](https://user-images.githubusercontent.com/124896653/218260481-24b9b10b-e671-412e-ab49-0aa6cd507f09.png)

**Comment by endrcn** [comment]
@hackerone-yusuf henüz PR kabul edilmedi.
