### ISSUE TITLE
Isınma Page 1 Invalid Count Value

### ISSUE THREAD

**Issue by hackerone-yusuf** [acikkaynak/deprem-io-backend#116]
![image](https://user-images.githubusercontent.com/124896653/218255613-0b5bf3ad-dcb7-447c-8e62-fe2a87e5b401.png)
#Soruna neyin neden olduğundan emin değilim bulursam ekleyeceğim

**Comment by izzetemredemir** [comment]
https://deprem-27jjydhzba-ew.a.run.app/yardim?page=1&limit=10&yardimTipi=isinma&
Bakacam buna

**Comment by izzetemredemir** [comment]
çözüldü
