### ISSUE TITLE
"Cannot read properties of undefined (reading 'split') Hatası

### ISSUE THREAD

**Issue by hackerone-yusuf** [acikkaynak/deprem-io-backend#120]
Şu an gıda ve enkazda bu hatayı veriyor.
![image](https://user-images.githubusercontent.com/124896653/218257008-5849c2ac-f4fd-43b8-b2a4-45b30ebefcf3.png)
![image](https://user-images.githubusercontent.com/124896653/218257018-07270b28-4f66-47fe-8070-d1025eed4211.png)

Eğer bakabilirseniz enkaz listesinde 14. öğeden kaynaklanıyor, ben göremiyorum.
![image](https://user-images.githubusercontent.com/124896653/218257349-f5dc0754-70e7-43c2-bd60-f1d563821168.png)
![image](https://user-images.githubusercontent.com/124896653/218257354-cc15c370-8257-436e-85cd-1d88d763f89f.png)

**Comment by izzetemredemir** [comment]
Bakacam

**Comment by mthocur** [comment]
@izzetemredemir sorun email mask eden kodda gibi gözüküyor;

[https://github.com/acikkaynak/deprem-io-backend/blob/4b5a10370776f6272ce461dac968a5925c4fe366/lib/Check.js#L19](https://github.com/acikkaynak/deprem-io-backend/blob/4b5a10370776f6272ce461dac968a5925c4fe366/lib/Check.js#L19)

[https://github.com/acikkaynak/deprem-io-backend/blob/4b5a10370776f6272ce461dac968a5925c4fe366/lib/Check.js#L21](https://github.com/acikkaynak/deprem-io-backend/blob/4b5a10370776f6272ce461dac968a5925c4fe366/lib/Check.js#L21)

**Comment by izzetemredemir** [comment]
Çözüldü
