### ISSUE TITLE
Data CSV export and Send email

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#122]
Veriyi csv olarak çıkartıp email atacak bir  enpoint lazım kendi emailiniz ile test edin tek bir email adresine mail atacak onu statik olarak paylaşacağım. Mevcut endpointleri değiştirmeyin

**Comment by izzetemredemir** [comment]
mail adresi birden fazla olacakmış

**Comment by halilturkoglucs** [comment]
Ilgili issue icin bir PR actim, umarim yardimci olur
https://github.com/acikkaynak/deprem-io-backend/pull/141
