### ISSUE TITLE
Length Limiti yok / adres, adres tarifi, kişi sayısı(?)

### ISSUE THREAD

**Issue by hackerone-yusuf** [acikkaynak/deprem-io-backend#124]
![image](https://user-images.githubusercontent.com/124896653/218262233-fc4c6d01-93b7-4998-b612-d2dbafd23b64.png)
![image](https://user-images.githubusercontent.com/124896653/218262376-647c85b2-1658-42af-9c3a-dda38294233d.png)
![image](https://user-images.githubusercontent.com/124896653/218262389-a65cbf66-470f-4083-8ac4-28a16f0237d1.png)

**Comment by izzetemredemir** [comment]
limit ekleyecem
