### ISSUE TITLE
`/ara-yardim` Endpoint Data Expose

### ISSUE THREAD

**Issue by toramanemre** [acikkaynak/deprem-io-backend#129]
`/ara-yardim` endpoint i tarafında herhangi bir filter verilmediğinde tüm data expose ediliyor. Data scrape önlenmesi için bu alanın gelen query e göre filtrelenmesi query yok ise data verilmemesi gerekiyor.

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/24626967/218267348-ef22477e-e89d-4150-a672-d4481645c8e8.png">

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/24626967/218267353-2bd1a081-123e-478a-9880-834ca0e3d961.png">

**Comment by endrcn** [comment]
PR açıldı.
