### ISSUE TITLE
REDIS_URL .env hatası

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#155]
AWS üzerinde production a geçmeye çalışıyoruz şöyle bir hata var 
![image](https://user-images.githubusercontent.com/11755605/218315749-14d00f59-a07d-4c68-95c8-df151b6ce2ab.png)

Şu şekilde updateler yaptım işe yaramadı
https://github.com/acikkaynak/deprem-io-backend/blob/main/config.js#L1-L15
https://github.com/acikkaynak/deprem-io-backend/blob/main/server/build.js#L22-L28

**Comment by OkanPinar** [comment]
ecs'ye .env file nasıl attach ediliyor? Ecs'deki task definition dan elle env varible olarak redis url vermeyi denediniz mi?
