### ISSUE TITLE
Add Redis Cache 

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#28]
* Redis varsa redis kurulumu, yoksa async-cache-dedupe kullanalim 
* Dockera eklenecek bunlar

**Comment by berkanyilm** [comment]
Kurulum yapılıp tüm yerlere uygulanacak mıdır ?

**Comment by izzetemredemir** [comment]
Tek docker imajı var

**Comment by anonrig** [comment]
fargate'e redis kurulup erisim bilgilerini paylasirsaniz ekleyeyim ben

**Comment by dogukanturan** [comment]
Redis tarafini hazirlayan varsa kullanilacak env iletirse docker compose tarafini konfigure edebilirim.

**Comment by anonrig** [comment]
Ben uzerine calisiyorum

**Comment by naugtur** [comment]
@anonrig how is it going? Can I help?

**Comment by anonrig** [comment]
hi @naugtur it would be good if we can replace the in memory caching with redis.

**Comment by naugtur** [comment]
I don't know how this is deployed, but I can add redis to docker-compose and replace cache.js
With Redis flushAll will not make sense.
I saw #111 - after that we can add some more cacheWrite calls and remove flushAll. Is it getting merged soon?

**Comment by anonrig** [comment]
env.example already has a redis key. I think production has redis right now. docker compose is mostly for local development. @izzetemredemir

**Comment by naugtur** [comment]
Ok. 
We can go with https://www.npmjs.com/package/@fastify/caching or https://www.npmjs.com/package/@fastify/redis and replace all caching entirely or use redis behind existing interface of #111 

Which do you prefer I do?

**Comment by anonrig** [comment]
Don't really have a preference both works fine

**Comment by naugtur** [comment]
Got redis cache working, now need to solve the flush.

**Comment by naugtur** [comment]
https://github.com/acikkaynak/deprem-io-backend/pull/139

**Comment by naugtur** [comment]
@anonrig 
Here:
https://github.com/acikkaynak/deprem-io-backend/commit/e8b7bb45b7b8396f3f55f66fda6c9362834cfcd9#diff-574e544af2813d930ff5f28dc8ea94d4e1efcfd8abd35281f03d45ecd5624a9aR94
Use selectifeFlush to avoid flushing individual items. You only need to flush list cache.
