### ISSUE TITLE
Backend ngram searchten yararlanabilir

### ISSUE THREAD

**Issue by alisomay** [acikkaynak/deprem-io-backend#31]
Search endpointleri su an icin structured data aliyor.
Eger indexing + ngram search implement edersek, konuyu dusunmeden insanlar keyword arayabilirler. 
Elimizdeki datayi indexleyip instancelarin lokal disk cacheinde tutmanin su dakikada problem olacagini zannetmiyorum.

Bu konuda hali hazirda gunluk olarak kullandigim ve tecrubem olan [tantivy](https://github.com/quickwit-oss/tantivy) kutuphanesini oneriyorum. 
Node js [bindingleri](https://github.com/strangerlabs/tantivy) de mevcut.

Eger benzer fikirlerdeyseniz ve database semasi belli ise neyi nasil indexleyecegimiz konusunda fikir yurutup bir PR ile gelebilirim. 

Boylece ngramlar uzerinden arama yaptigimizda
`filtrele` -> `listelere ulas` modelini
`dusundugunu yaz` -> `aradigini bul` modeline gecirebiliriz.

**Comment by alisomay** [comment]
Bu teklifin yarar saglayacagini dusunuyorsaniz. Backend uzerinde aktif calisan bir contributor ile iletisime gecebiliriz. 
Ya issue uzerinden ya da discord uzerinden `Ali Somay` olarak ulasabilirsiniz. 

Elinize saglik 🙏

**Comment by izzetemredemir** [comment]
Ne kadar memory/disk tüketiyor? Docker containerını gereksiz şişirsin istemem
Ayrı bir endpoint olarak yayına almak mantıklı.

**Comment by alisomay** [comment]
Bende benzer dusunuyorum. Eger ayri bir endpoint olur ise daha da kolay olur cunku boylece Rust ile de yazabilirim.
Disk ve memory tuketimi konusu soyle.

Indexing sirasinda gecici olarak bir memory consumption oluyor ama indexing suresini arttirip concurrencyi dusurerek bu memory consumptioni kontrol altinda tutmak kolay. 

Indexler diskte duruyor ve memory mapped directory olarak calisiyor bu sebepten search sirasinda konusmaya deger bir memory tuketimi yok.

Disk tuketimi ise tamamen datanin buyuklugune ve nekadarini indexlemek istedigimize bagli.
Bu konularda bilgi alabilirsem disk tuketimi konusunda tahminler sunabilirim. 

https://fulmicoton.com/posts/behold-tantivy/
Burada daha da fazla bilgi bulabilirsiniz.

**Comment by alisomay** [comment]
Kabaca buyuk ihtimal ile soyle olur.
Ayri servis olarak deploy edilir ise,
- Belirli araliklar ile db poll edilir
- Son indexlenen girdilerin timestampleri diskte tutulur
- Yeni girdiler ile index guncellenir
- Search requestler index uzerinde search edildikten sonra, db doc ya da row idleri doner
- Bu rowlar ya da doclar dbden cekilir ve dondurulur.

**Comment by alisomay** [comment]
Implementasyon suresi servis durumunda deploymenttan gayri olarak tahmini olarak 1 gun en fazla 1.5 gunu bulur.

**Comment by alisomay** [comment]
```json
  "family": "depremio-TD",
  "executionRoleArn": "arn:aws:iam::366354050833:role/ecsServiceRole",
  "networkMode": "awsvpc",
  "volumes": [],
  "placementConstraints": [],
  "requiresCompatibilities": [
    "FARGATE"
  ],
  "cpu": "2048",
  "memory": "4096",
  "tags": []
```
Gerci specler ayni containerda calistirmak icin de yeterli gibi. 
Storage ne kadar bilmiyorum tabi.

**Comment by izzetemredemir** [comment]
Şuan bunu ekleyemeyiz
