### ISSUE TITLE
null check for request inputs

### ISSUE THREAD

**Issue by kadirkurhan** [acikkaynak/deprem-io-backend#35]
tüm endpointlerde her türlü exception'a karşı try-catch ile önlem alınmış fakat try catch maliyetli bir çözüm ve sorunsuz çalışan bir senaryoda dahi yavaşlamaya neden oluyor. yoğun trafik alabilecek bir uygulamada bunun önüne geçmek için try-catch'i yalnızca db connection'ın yapıldığı noktalarda kullanmalı, null check'i ise if kontrolleriyle yapmalıyız.
örnek olması açısından:

if(request==null)
  return badrequest;
try
{
  db.getall();
}catch{
  return internalerror;
}

**Comment by izzetemredemir** [comment]
Test edemediğimiz bir senaryoda proje patlasın istemiyorum. Test edildikten sonra ürün optimize ederiz.
