### ISSUE TITLE
YardimKaydi formuna telefon checki eklenecek

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#36]
Diğer Modeller için var yardimKaydi için telefon numarası kontrolü eklenecek

**Comment by izzetemredemir** [comment]
Tamamdır lib/Check.js işine yarar

**Comment by endrcn** [comment]
Check class'ı eklemiştim içinde isPhoneNumber metodunu kullanabilir/geliştirebilirsiniz.

**Comment by berkanyilm** [comment]
Tamamdır

**Comment by berkanyilm** [comment]
merhaba, dediğiniz gibi Check class'nı kullandım.
Pr attım bilginize.

**Comment by izzetemredemir** [comment]
mergeledim teşekkürler
