### ISSUE TITLE
Kullanıcı eposta bilgisi gizlenmesi

### ISSUE THREAD

**Issue by mehmetik** [acikkaynak/deprem-io-backend#41]
tüm sayfalarda gizlenen isim, telefon bilgilerinin yanında e-posta bilgisininde çıktısının gizlenmesi gerekiyor.

**Comment by berkanyilm** [comment]
Bunu ben alıyorum.

**Comment by mehmetik** [comment]
mail@example.com m***@e*****.c*** şeklinde olursa sevinirim 👍

**Comment by berkanyilm** [comment]
Fastify'a geçtikten sonra yeniden revize edilmiş olup, istek dönen ve isteklerin içinde email bilgisi olan datalar m***@e*****.c*** şeklinde gizlenmiştir. Bilginize.

**Comment by hackerone-yusuf** [comment]
Adda boşluk yoksa gizlemiyor.
![image](https://user-images.githubusercontent.com/124896653/218258261-67169d83-6f4b-4c04-b26c-abbcd3c54a3e.png)
