### ISSUE TITLE
Yardimkaydi endpoint eksik!

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#45]
Yardimkaydi şuan sadece yardim modeli için var ama aynı form yardımEt içinde var o enpoint eksik

**Comment by izzetemredemir** [comment]
Ben bakıyorum

**Comment by hsyngul** [comment]
@izzetemredemir alıyorum bunu

**Comment by berkanyilm** [comment]
Ben aldım bunu.

**Comment by berkanyilm** [comment]
Hangi endpoint'in olduğu belli mi ?

**Comment by izzetemredemir** [comment]
/ekleYardimKaydi  var  bu sadece yardım modeline ekliyor  bunun yardımEtModel için olanı lazım
ekleYardimEtKaydi şeklinde

**Comment by mehmetik** [comment]
Eğer kimse de yoksa ben alıyorum bunu

**Comment by izzetemredemir** [comment]
Hallettim
