### ISSUE TITLE
yardim saglayanlarda emai field'i gozukmuyor

### ISSUE THREAD

**Issue by fatihozdil** [acikkaynak/deprem-io-backend#47]
![image](https://user-images.githubusercontent.com/72515197/218104030-034bcdb4-09ec-4229-9726-5ddbaed62805.png)

url :https://deprem-27jjydhzba-ew.a.run.app/yardimet/63e63c64a6f9a9a9c075e267

**Comment by mehmetik** [comment]
daha önce böyle bir field açılmamıştı. Frontend tarafında giriş isteği var mı? Varsa model'e ekleyelim. mevcut scheme'da yok.

**Comment by mehmetik** [comment]
> ![image](https://user-images.githubusercontent.com/72515197/218104030-034bcdb4-09ec-4229-9726-5ddbaed62805.png)
> 
> url :https://deprem-27jjydhzba-ew.a.run.app/yardimet/63e63c64a6f9a9a9c075e267

fields alanını kullanabilirsin o noktada 👍
