### ISSUE TITLE
google map linkin backend'de eklenmesi

### ISSUE THREAD

**Issue by fatihozdil** [acikkaynak/deprem-io-backend#48]
![image](https://user-images.githubusercontent.com/72515197/218104700-001af461-a19a-451a-b147-f63a3b265825.png)

url : https://deprem-27jjydhzba-ew.a.run.app/yardim/63e644a8cedf55010067192d

google map linki bos geliyor

**Comment by izzetemredemir** [comment]
google maps linki eklenmiyor şuan frontendden alan db de boş olabilir

**Comment by mehmetik** [comment]
/yardim post'unda googleMapLink gönderilmedi ise boş görünmesi normal

**Comment by izzetemredemir** [comment]
Burada sorun yok gibi frontende eklenince yeniden test ederiz

**Comment by fatihozdil** [comment]
post requestte googleMap link gonderme secenegi yok adrese gore db de ekleme ihtimalimiz yok mu ?
@mehmetik @izzetemredemir

**Comment by izzetemredemir** [comment]
https://deprem-27jjydhzba-ew.a.run.app/yardim/63e64b059e71166b878f61ba
