### ISSUE TITLE
yolcu tasima yardimi bad request 

### ISSUE THREAD

**Issue by fatihozdil** [acikkaynak/deprem-io-backend#60]
![image](https://user-images.githubusercontent.com/72515197/218122828-a8ebe015-fd01-4aa1-acea-abec594466ee.png)
![image](https://user-images.githubusercontent.com/72515197/218123120-5126edc8-d531-45f9-8748-c5aaeee9de3b.png)
https://deprem-27jjydhzba-ew.a.run.app/yardimet

**Comment by izzetemredemir** [comment]
https://deprem-27jjydhzba-ew.a.run.app/yardimet?yardimTipi=yolcuTasima

**Comment by fatihozdil** [comment]
anlamadim
