### ISSUE TITLE
Post methodlarında telefon numalarında sıkıntı var

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#66]
* telefon numaları 0 ile başlayabilir yani 11 ve 10 karakterli olabilir
* telefon numarası olmak zorunda değil  
* telefon field ı "" şekilinde boş gelebilir 
Fonksiyonu bunları tolere edecek şekilde değiştirin

**Comment by hsyngul** [comment]
bunu alabilirim @izzetemredemir

**Comment by endrcn** [comment]
@hsyngul ben PR açtım.

**Comment by hackerone-yusuf** [comment]
Boş girip request attığımda hataya yol açmıyor fakat sisteme işleniyor.
![image](https://user-images.githubusercontent.com/124896653/218253882-7d36a8e8-a2df-4fd2-ade6-8a6302673fb2.png)
