### ISSUE TITLE
/ekleYardimKaydi çalışmıyor 

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#69]
/ekleYardimKaydi çalışmıyor  ama 200 dönüyor

**Comment by endrcn** [comment]
@izzetemredemir son merge'den sonra çalışıyor olmalı. Localde denedim 200 veriyor ve DB kaydını yapıyor. Gönderdiğin request nedir ?

**Comment by izzetemredemir** [comment]
cache temizlenmiyor sıkıntı oymuş

**Comment by izzetemredemir** [comment]
redis ile çözülecek bu sorun
