### ISSUE TITLE
Şehir kısmına ilçe eklenecek

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#7]
Adreste şehir, hedefşehir gibi kısımlar var ama ilçe yok onun düzeltilmesi lazım

**Comment by khnbzkrt** [comment]
@izzetemredemir bana assign edebilirsin

**Comment by khnbzkrt** [comment]
PR oluşturuldu fyi.

**Comment by izzetemredemir** [comment]
> PR oluşturuldu fyi.

Yardım model içinde ekler misin ilçe alanını geçici olarak required false olsun

**Comment by khnbzkrt** [comment]
@izzetemredemir orası direkt text input olarak açık adres alıyor. Onu ayrı bir issue ile il-ilçe ve adres detayına döndürmek lazım sanırım.

**Comment by izzetemredemir** [comment]
Tamamdır teşekkür ederim
