### ISSUE TITLE
/ara-yardim 404

### ISSUE THREAD

**Issue by izzetemredemir** [acikkaynak/deprem-io-backend#90]
Örnek query `https://deprem-27jjydhzba-ew.a.run.app/ara-yardim/?q=&yardimDurumu=&yardimTipi=gida&acilDurum=orta&aracDurumu=& `

404 dönüyor filtreleme kısmında

**Comment by endrcn** [comment]
`ara-yardim/?q=&yardimDurumu=&yardimTipi=gida&acilDurum=orta&aracDurumu=&`

yerine

`ara-yardim?q=&yardimDurumu=&yardimTipi=gida&acilDurum=orta&aracDurumu=&`

kullanınca cevap veriyor. ? öncesindeki / bozuyor.

**Comment by anonrig** [comment]
Fastify ayarlarinda `ignoreTrailingSlash` ayarini `true` yaparsak bu sorun cozulur.

Doc: https://www.fastify.io/docs/latest/Reference/Server/#ignoretrailingslash
